# Generated by Django 5.0.6 on 2024-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinstitutoDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='DNI',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
